### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by VRSandeep** [ondoheer/Sublime-YAPF#1]
I am using ST2. It seems ST2 uses python 2.6 version by default, that's why context menu button is disabled. In console, it throws 
`File "./yapf-0.1.4/yapf/__init__.py", line 29, in <module>
    import argparse
ImportError: No module named argparse`

**Comment by ondoheer** [comment]
Hello VRSandeed, Your are right.

I stoped the developing of this plugin because https://github.com/jason-kane/PyYapf was released with far more suppport than this little experiment! You can find thatone in the official sublime package repo.!
